### ISSUE TITLE
Position still broken

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/RewardZ#1]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

1.0.1

### Describe the Issue

Button shows and clickable in wrong position

Hoverable and tooltip work in right position

### latest.log

nope

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RewardZ/commit/bfe57713aacfd38c697f1188a9943de49cc20dd0](https://github.com/Globox1997/RewardZ/commit/bfe57713aacfd38c697f1188a9943de49cc20dd0)
